### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by bblackbelt** [alter-ego/androidbound#100]
```
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5105)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at java.util.AbstractCollection.toString(AbstractCollection.java:372)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at solutions.alterego.androidbound.helpers.reflector.PropertyInfo.setValue(PropertyInfo.java:103)
       at solutions.alterego.androidbound.binding.types.PropertyBinding.setValue(PropertyBinding.java:68)
       at solutions.alterego.androidbound.binding.types.TargetPropertyBinding.access$201(TargetPropertyBinding.java:6)
       at solutions.alterego.androidbound.binding.types.TargetPropertyBinding.lambda$setValue$0(TargetPropertyBinding.java:26)
       at solutions.alterego.androidbound.binding.types.TargetPropertyBinding$$Lambda$1.call(Unknown Source)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5105)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mrsasha** [comment]
can you check if this has been fixed in the 0.7.1 release?

**Comment by bblackbelt** [comment]
of course. I will let you know

**Comment by bblackbelt** [comment]
@mrsasha it still happening on 0.7.1

**Comment by mrsasha** [comment]
ok, I replaced the map with `ConcurrentHashMap`, that should work better. it'll be in release 0.7.3

**Comment by bblackbelt** [comment]
still happening on 0.7.3 :(

**Comment by bblackbelt** [comment]
```
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at java.util.AbstractCollection.toString(AbstractCollection.java:372)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at solutions.alterego.androidbound.helpers.reflector.PropertyInfo.setValue(PropertyInfo.java:95)
       at solutions.alterego.androidbound.binding.types.PropertyBinding.setValue(PropertyBinding.java:68)
       at solutions.alterego.androidbound.binding.types.TargetPropertyBinding.access$201(TargetPropertyBinding.java:6)
       at solutions.alterego.androidbound.binding.types.TargetPropertyBinding.lambda$setValue$0(TargetPropertyBinding.java:26)
       at solutions.alterego.androidbound.binding.types.TargetPropertyBinding$$Lambda$1.call(Unknown Source)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
