### ISSUE TITLE
Exception java.lang.NoClassDefFoundError: android.graphics.drawable.Icon with latest support library

### ISSUE THREAD

**Issue by mrsasha** [alter-ego/androidbound#133]
Seems connected to this: https://issuetracker.google.com/issues/63151548.

```
java.lang.NoClassDefFoundError: android.graphics.drawable.Icon
at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
    at java.lang.Class.getDexCacheType(Class.java:479)
    at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:236)
    at java.lang.reflect.ArtMethod.getParameterTypes(ArtMethod.java:176)
    at java.lang.reflect.Method.getParameterTypes(Method.java:174)
    at solutions.alterego.androidbound.helpers.reflector.MethodInfo.<init>(MethodInfo.java:25)
    at solutions.alterego.androidbound.helpers.Reflector.getMethodsForClass(Reflector.java:445)
    at solutions.alterego.androidbound.helpers.Reflector.getAllMethods(Reflector.java:327)
    at solutions.alterego.androidbound.helpers.Reflector.getMethods(Reflector.java:358)
    at solutions.alterego.androidbound.helpers.Reflector.findGetterWithPrefix(Reflector.java:164)
    at solutions.alterego.androidbound.helpers.Reflector.findGetterWithGetPrefix(Reflector.java:159)
    at solutions.alterego.androidbound.helpers.Reflector.getProperty(Reflector.java:101)
    at solutions.alterego.androidbound.binding.types.PropertyBinding.<init>(PropertyBinding.java:18)
    at solutions.alterego.androidbound.binding.types.TargetPropertyBinding.<init>(TargetPropertyBinding.java:13)
    at solutions.alterego.androidbound.factories.TargetBindingFactory.createLeaf(TargetBindingFactory.java:15)
    at solutions.alterego.androidbound.factories.SourceBindingFactory.create(SourceBindingFactory.java:33)
    at solutions.alterego.androidbound.factories.SourceBindingFactory.create(SourceBindingFactory.java:23)
    at solutions.alterego.androidbound.binding.BindingAssociationEngine.createTargetBinding(BindingAssociationEngine.java:146)
    at solutions.alterego.androidbound.binding.BindingAssociationEngine.<init>(BindingAssociationEngine.java:52)
    at solutions.alterego.androidbound.binding.TextSpecificationBinder.bind(TextSpecificationBinder.java:48)
    at solutions.alterego.androidbound.ViewBinder.bindViewToSource(ViewBinder.java:211)
    at solutions.alterego.androidbound.android.BindableLayoutInflaterFactory$InflaterFactory2Base.bindView(BindableLayoutInflaterFactory.java:150)
    at solutions.alterego.androidbound.android.BindableLayoutInflaterFactory$3.onCreateView(BindableLayoutInflaterFactory.java:91)
    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:178)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
    at solutions.alterego.androidbound.ViewBinder.inflate(ViewBinder.java:312)
    at solutions.alterego.androidbound.android.adapters.BindableListAdapter.inflateViewForObject(BindableListAdapter.java:119)
    at solutions.alterego.androidbound.android.adapters.BindableListAdapter.getView(BindableListAdapter.java:87)
    at android.widget.AbsListView.obtainView(AbsListView.java:2823)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1290)
    at android.widget.ListView.onMeasure(ListView.java:1202)
    at android.view.View.measure(View.java:18596)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1082)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:614)
    at android.view.View.measure(View.java:18596)
    at android.widget.RelativeLayout.measureChild(RelativeLayout.java:698)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:482)
    at android.view.View.measure(View.java:18596)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
    at android.view.View.measure(View.java:18596)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
at android.view.View.measure(View.java:18596
```

**Comment by mrsasha** [comment]
fixed with #134
