### ISSUE TITLE
another ` java.lang.NoClassDefFoundError: android/graphics/drawable/Icon` in Reflector

### ISSUE THREAD

**Issue by mrsasha** [alter-ego/androidbound#136]
08-09 12:29:20.169 5467-5467/org.sharethemeal.app.android E/AndroidRuntime: FATAL EXCEPTION: main
  java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
    at java.lang.Class.getDeclaredMethods(Native Method)
    at java.lang.Class.getPublicMethodsRecursive(Class.java:824)
    at java.lang.Class.getMethods(Class.java:807)
    at solutions.alterego.androidbound.helpers.Reflector.getMethodsForClass(Reflector.java:439)
    at solutions.alterego.androidbound.helpers.Reflector.getAllMethods(Reflector.java:327)
    at solutions.alterego.androidbound.helpers.Reflector.getMethods(Reflector.java:358)
    at solutions.alterego.androidbound.helpers.Reflector.findGetterWithPrefix(Reflector.java:164)
    at solutions.alterego.androidbound.helpers.Reflector.findGetterWithGetPrefix(Reflector.java:159)
    at solutions.alterego.androidbound.helpers.Reflector.getProperty(Reflector.java:101)
    at solutions.alterego.androidbound.binding.types.PropertyBinding.<init>(PropertyBinding.java:18)
    at solutions.alterego.androidbound.binding.types.TargetPropertyBinding.<init>(TargetPropertyBinding.java:13)
    at solutions.alterego.androidbound.factories.TargetBindingFactory.createLeaf(TargetBindingFactory.java:15)
    at solutions.alterego.androidbound.factories.SourceBindingFactory.create(SourceBindingFactory.java:33)
    at solutions.alterego.androidbound.factories.SourceBindingFactory.create(SourceBindingFactory.java:23)
    at solutions.alterego.androidbound.binding.BindingAssociationEngine.createTargetBinding(BindingAssociationEngine.java:146)
    at solutions.alterego.androidbound.binding.BindingAssociationEngine.<init>(BindingAssociationEngine.java:52)
    at solutions.alterego.androidbound.binding.TextSpecificationBinder.bind(TextSpecificationBinder.java:48)
    at solutions.alterego.androidbound.ViewBinder.bindViewToSource(ViewBinder.java:211)
    at solutions.alterego.androidbound.android.BindableLayoutInflaterFactory$InflaterFactory2Base.bindView(BindableLayoutInflaterFactory.java:150)
    at solutions.alterego.androidbound.android.BindableLayoutInflaterFactory$3.onCreateView(BindableLayoutInflaterFactory.java:91)
    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:169)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at solutions.alterego.androidbound.ViewBinder.inflate(ViewBinder.java:312)
    at solutions.alterego.androidbound.android.adapters.BindableListAdapter.inflateViewForObject(BindableListAdapter.java:119)
    at solutions.alterego.androidbound.android.adapters.BindableListAdapter.getView(BindableListAdapter.java:87)
    at android.widget.AbsListView.obtainView(AbsListView.java:2177)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1247)
    at android.widget.ListView.onMeasure(ListView.java:1159)
    at android.view.View.measure(View.java:15881)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5023)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
    at android.view.View.measure(View.java:15881)
    at android.widget.RelativeLayout.measureChild(RelativeLayout.java:698)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:494)
    at android.view.View.measure(View.java:15881)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
    at android.view.View.measure(View.java:15881)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
    at android.view.View.measure(View.java:15881)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5023)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                            	at andr

**Comment by mrsasha** [comment]
this one now crashes on huawei with 4.3.
