### ISSUE TITLE
viewresolver shouldn't crash for unknown classes

### ISSUE THREAD

**Issue by mrsasha** [alter-ego/androidbound#63]
```
10-11 08:17:05.077: D/SHARETHEMEAL(4185): ViewResolver.resolveName() @ line 117: Resolving rg.sharethemeal.app.ui.bindable.ExtendedBindableButton with rg.sharethemeal.app.ui.bindable.ExtendedBindableButton
10-11 08:17:05.078: W/SHARETHEMEAL(4185): ViewResolver.createView() @ line 73: View not found for name rg.sharethemeal.app.ui.bindable.ExtendedBindableButton
```

wrong package name made `ViewBinder` crash.

```
10-11 08:17:04.523: E/SHARETHEMEAL(4185): PropertyInfo.getValue() @ line 52: Reflector getValue exception = java.lang.NullPointerException: iterable must not be null
10-11 08:17:05.429: E/AndroidRuntime(4185): FATAL EXCEPTION: main
10-11 08:17:05.429: E/AndroidRuntime(4185): Process: org.sharethemeal.app.android, PID: 4185
10-11 08:17:05.429: E/AndroidRuntime(4185): android.view.InflateException: Binary XML file line #2: Error inflating class rg.sharethemeal.app.ui.bindable.ExtendedBindableButton
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at solutions.alterego.androidbound.ViewBinder.inflate(ViewBinder.java:259)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at solutions.alterego.androidbound.android.ui.BindableListItemView.<init>(BindableListItemView.java:32)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at solutions.alterego.androidbound.android.adapters.BindableListAdapter.inflateViewForObject(BindableListAdapter.java:92)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at solutions.alterego.androidbound.android.adapters.BindableListAdapter.getView(BindableListAdapter.java:79)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.AbsListView.obtainView(AbsListView.java:2347)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.ListView.onMeasure(ListView.java:1154)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1411)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:479)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:629)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:389)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.View.measure(View.java:17547)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.Choreographer.doFrame(Choreographer.java:550)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.os.Handler.handleCallback(Handler.java:739)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at android.os.Handler.dispatchMessage(Handler.java:95)
10-11 08:17:05.429: E/AndroidRuntime(4185):     at and
```

**Comment by mrsasha** [comment]
This turns out to be an XML inflater error, so nothing that can be fixed on this end: 

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "olutions.alterego.androidbound.android.ui.BindableTextView" on path: DexPathList[[zip file "/data/app/solutions.alterego.androidbound.example-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/l
```
